[project]
name = "flync"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "biopython>=1.85",
    "cpat>=3.0.5",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "pyarrow>=20.0.0",
    "pybigwig>=0.3.24",
    "pyfaidx>=0.8.1.4",
    "pyranges>=0.1.4",
    "pyyaml>=6.0.2",
    "scipy>=1.15.3",
    "viennarna>=2.7.0",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
