# Feature configs
features:
  bwq:
    threads: 4
  cpat:
    workers: 4
  kmer:
    batch_size: 10000
    k_max: 12
    k_min: 3
    output_format: sparse
    workers: 4
  mfe:
    batch_size: 1000
    workers: 4

# BWQ
bwq_config: /home/chlab/flync/src/config/bwq_config.yaml

# CPAT
hexamer_table: /home/chlab/flync/src/config/fly_Hexamer.tsv
logit_model: /home/chlab/flync/src/config/Fly_logitModel.RData
reference_fasta: /home/chlab/flync/new-tests/Drosophila_melanogaster.BDGP6.46.dna.toplevel.fa

# KMER
use_sparse: true

# General behaviour
keep_intermediates: false
unify: true
